#!/bin/bash

# Ethernet
eth_state="$(cat /sys/class/net/eth0/operstate)"
eth_ip=$(ip -o -4 addr show dev eth0 | awk -F '[ /]+' '/global/ {print $4}')
if [ "$eth_state" = "up" ]; then
    ETH="  $eth_ip "
else
    ETH=" No IP"
fi

# Wireless
wlan_state="$(cat /sys/class/net/wlan0/operstate)"
wlan_ip=$(ip -o -4 addr show dev wlan0 | awk -F '[ /]+' '/global/ {print $4}')
if [ "$wlan_state" = "up" ]; then
    WLAN="  $wlan_ip "
else
    WLAN=" No IP"
fi

# Battery
BAT_STATE=$(acpi | awk '{print $3}' | sed 's/,//g')
BAT_RAW=$(acpi | awk '{print $4}' | sed 's/%,//g')
if [[ "$BAT_STATE" == "Charging" ]]; then
    BAT="  $BAT_RAW% "
elif [[ "$BAT_STATE" == "Full" ]]; then
    BAT="  Capacity "
elif [[ "$BAT_STATE" == "Discharging" ]]; then
    if [[ "$BAT_RAW" -lt "5" ]]; then
        BAT=" $BAT_RAW%"
    elif [[ "$BAT_RAW" -lt "25" ]]; then
        BAT=" $BAT_RAW%"
    elif [[ "$BAT_RAW" -lt "50" ]]; then
        BAT=" $BAT_RAW%"
    elif [[ "$BAT_RAW" -lt "85" ]]; then
        BAT="  $BAT_RAW% "
    else
        BAT="  $BAT_RAW% "
    fi
fi

# Time
DATE=" $( date +"%F %T")"

# Audio
AUDIO_STATE=$(amixer sget Master | egrep -m 1 'Playback.*?\[o' | egrep -o '\[o.+\]')
RAW_AUDIO=$(amixer sget Master | egrep -o -m 1 "[0-9]+"% | sed 's/%//g')
if [[ $AUDIO_STATE == '[off]' ]]; then
    AUDIO=" Muted"
elif [[ $RAW_AUDIO == 0 ]]; then
    AUDIO="  $RAW_AUDIO% "
elif [[ $RAW_AUDIO -lt 51 ]]; then
    AUDIO="  $RAW_AUDIO% "
else
    AUDIO="  $RAW_AUDIO% "
fi

# HDD
DRIVE="${BLOCK_INSTANCE:-$HOME}"
SPACE=$(df -h -P -l "$DRIVE" | awk '/\/.*/ {print $4; use=$5; }')

# Brightness
BRIGHTNESS="  $(cat /sys/class/backlight/intel_backlight/brightness)% "

# locker
LOCKER_RAW=$(xset q | grep timeout | awk '{print $2}')
if [ $LOCKER_RAW == 300 ]; then
    LOCKER_STATUS="  true "
else
    LOCKER_STATUS=" false"
fi

#PRINT
echo  " "$SPACE "|$ETH|$WLAN|$BAT|$BRIGHTNESS|$LOCKER_STATUS|$AUDIO|$DATE"
